server:
  port: 9003
spring:
  application:
    name: tensquare‐qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.62.102:3306/tensquare_qa?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /**/**
      - /bank/**
      - /user/**
      - /cms/authCode/**
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath:mapper/*/*.xml
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    map-underscore-to-camel-case: true
  type-aliases-package: com.tensquare.qa.pojo
logging:
  level:
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    service‐url:
      defaultZone: http://localhost:6868/eureka/
