server:
  port: 9002
spring:
  application:
    name: tensquare‐recruit
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.62.102:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  redis:
    port: 6379
    host: 121.89.192.72
    database: 0
    password: password
    timeout: 1000ms
    lettuce:
      pool:
       max-active: 10
       min-idle: 5
       max-idle: 10
       max-wait: 2000ms


secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /**/**
      - /bank/**
      - /user/**
      - /cms/authCode/**
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
logging:
  level:
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka